services:
  goma-gateway:
    image: jkaninda/goma-gateway
    command: server
    healthcheck:
      test: curl -f http://localhost:8080/health/live || exit 1
      interval: 30s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./:/etc/goma/
